language: android

#install: true


script:
- ./gradlew clean #--continue brickatorBuildCoverageReport brickatorUpdateCoverageReport
android:
  components:
    # Uncomment the lines below if you want to
    # use the latest revision of Android SDK Tools
     - platform-tools
     - tools

    # The BuildTools version used by your project
    - build-tools-22.0.1 

    # The SDK version used to compile your project
    - android-22  # travis only handles api 22 atm

    # Additional components
    #- extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository
    #- addon-google_apis-google-19

    # Specify at least one system image,
    # if you need to run emulator(s) during your tests
    #- sys-img-armeabi-v7a-android-22
    - sys-img-x86-android-22
before_script:
    - wget http://services.gradle.org/distributions/gradle-2.14.1-bin.zip
    - unzip gradle-2.14.1-bin.zip
    - export GRADLE_HOME=$PWD/gradle-2.14.1
    - export PATH=$GRADLE_HOME/bin:$PATH

    
